# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssacount', '0005_ssacount_server_aes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssacount',
            name='server_aes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
